<?php
use Skyline\Navigation\NavigationBarItem;
use Skyline\Render\Context\DefaultRenderContext;

/**
 * @var DefaultRenderContext $this
 * @var NavigationBarItem $item
 */

$item = $this->getAdditionalInfo()[0];
$tmpCallback = $this->getAdditionalInfo()[1];

$title = $item->getTitle();
$action = $item->getAction();

?>
<li class="nav-item<?=$item->isSelected()?' active':''?>">
    <?php
    if($item->isEnabled() == false) {
        ?>
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true"><?=$title?></a>
        <?php
    } else {
        ?>
        <a class="nav-link" href="<?=$action ? $action->getExportedActionVersion(): '#'?>"><?=$title?></a>
        <?php
    }
    ?>
</li>
